#!/usr/bin/env python3
"""Generate/check plan statistics and three Markdown views without inventing state."""

import argparse
from copy import deepcopy
from html import escape
from pathlib import Path
import sys

import yaml

from validate_project_state import ROOT, UniqueKeyLoader, derive_summary, validate


def cell(value):
    if isinstance(value, list):
        value = ", ".join(str(v) for v in value) or "—"
    return escape(str(value if value is not None else "—")).replace("|", "&#124;").replace("\n", "<br>")


def render(plan):
    """Pure rendering; all ordering is deterministic and all state comes from YAML."""
    project, summary = plan["project"], derive_summary(plan)
    features = sorted(plan["features"], key=lambda f: f["id"])
    header = (
        "<!-- Generated by scripts/render_project_views.py; do not edit manually. -->\n\n"
        f"计划 revision：{cell(project['plan_revision'])}；状态：{cell(project['status'])}；"
        f"完整性：{cell(summary['plan_completeness'])}。\n\n"
    )
    empty = "尚未规划 Feature；空视图不代表已批准、可执行或已完成。\n"
    backlog = "# Backlog\n\n" + header
    dependency = "# Dependency Map\n\n" + header
    milestones = "# Milestones\n\n" + header
    if not features:
        return {"backlog.md": backlog + empty, "dependency-map.md": dependency + empty,
                "milestones.md": milestones + empty}

    backlog += "| ID | 能力 | 类型 | 优先级 | 状态 | 依赖 | 阻塞决策 | 需求来源 |\n| --- | --- | --- | --- | --- | --- | --- | --- |\n"
    for f in features:
        values = [f["id"], f.get("title"), f.get("kind"), f.get("priority"), f["status"],
                  f["depends_on"], f.get("blocking_decisions", []), f.get("requirements", [])]
        backlog += "| " + " | ".join(cell(v) for v in values) + " |\n"
    backlog += "\n统计：" + "；".join(f"{s}={n}" for s, n in summary["counts"].items()) + "。\n"

    # Mermaid labels use validated IDs only. User-authored titles stay in escaped tables.
    nodes = {f["id"]: f"n{i}" for i, f in enumerate(features)}
    dependency += "箭头从前置 Feature 指向依赖它的 Feature。\n\n```mermaid\nflowchart TD\n"
    for f in features:
        dependency += f'    {nodes[f["id"]]}["{f["id"]}"]\n'
    for f in features:
        for dep in sorted(f["depends_on"]):
            dependency += f'    {nodes[dep]} --> {nodes[f["id"]]}\n'
    dependency += "```\n"

    milestones += "| 里程碑 | Feature | DONE / 总数 | 状态分布 |\n| --- | --- | --- | --- |\n"
    groups = {}
    for f in features:
        groups.setdefault(str(f.get("milestone") or "未分配"), []).append(f)
    for name, members in sorted(groups.items()):
        counts = {}
        for f in members:
            counts[f["status"]] = counts.get(f["status"], 0) + 1
        values = [name, [f["id"] for f in members], f"{counts.get('DONE', 0)} / {len(members)}",
                  ", ".join(f"{s}={n}" for s, n in sorted(counts.items()))]
        milestones += "| " + " | ".join(cell(v) for v in values) + " |\n"
    milestones += "\n计数不替代验收、批准或发布授权；CANCELLED 不计入 DONE。\n"
    return {"backlog.md": backlog, "dependency-map.md": dependency, "milestones.md": milestones}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--plan", type=Path, default=ROOT / "docs/project/project-plan.yaml")
    parser.add_argument("--root", type=Path, default=ROOT, help="Root for evidence paths")
    parser.add_argument("--output-dir", type=Path, help="Default: the plan's directory")
    parser.add_argument("--write", action="store_true", help="Update derived counts/views; default is read-only check")
    args = parser.parse_args()
    try:
        original = yaml.load(args.plan.read_text(encoding="utf-8"), Loader=UniqueKeyLoader)
        plan = deepcopy(original)
        plan["planning_status"] = derive_summary(plan)
        errors = validate(plan, root=args.root)
        if errors:
            raise ValueError("; ".join(errors))
        output = args.output_dir or args.plan.parent
        views = render(plan)
        stale = [name for name, body in views.items()
                 if not (output / name).is_file() or (output / name).read_text(encoding="utf-8") != body]
        summary_changed = original["planning_status"] != plan["planning_status"]
        if not args.write:
            if stale or summary_changed:
                print(f"PROJECT VIEWS STALE: statistics={summary_changed}; files={', '.join(stale)}", file=sys.stderr)
                return 1
            print("PROJECT VIEWS VALID")
            return 0
        output.mkdir(parents=True, exist_ok=True)
        if summary_changed:
            # Only derived values change; PyYAML may normalize layout/comments when rewriting.
            args.plan.write_text(yaml.safe_dump(plan, allow_unicode=True, sort_keys=False), encoding="utf-8")
        for name in stale:
            (output / name).write_text(views[name], encoding="utf-8")
        print(f"PROJECT VIEWS UPDATED: statistics={summary_changed}; files={len(stale)}")
        return 0
    except (OSError, KeyError, TypeError, AttributeError, ValueError, yaml.YAMLError) as exc:
        print(f"PROJECT VIEWS INVALID: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
